//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LECmd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LECmd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00-00-00	XEROX CORPORATION
        ///00-00-01	XEROX CORPORATION
        ///00-00-02	XEROX CORPORATION
        ///00-00-03	XEROX CORPORATION
        ///00-00-04	XEROX CORPORATION
        ///00-00-05	XEROX CORPORATION
        ///00-00-06	XEROX CORPORATION
        ///00-00-07	XEROX CORPORATION
        ///00-00-08	XEROX CORPORATION
        ///00-00-09	XEROX CORPORATION
        ///00-00-0A	OMRON TATEISI ELECTRONICS CO.
        ///00-00-0B	MATRIX CORPORATION
        ///00-00-0C	CISCO SYSTEMS, INC.
        ///00-00-0D	FIBRONICS LTD.
        ///00-00-0E	FUJITSU LIMITED
        ///00-00-0F	NEXT, INC.
        ///00-00-10	SYTEK INC.
        ///00-00-11	NORMEREL SYSTEMES
        ///00-00-12	INF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MACs {
            get {
                return ResourceManager.GetString("MACs", resourceCulture);
            }
        }
    }
}
