//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LECmd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LECmd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00-00-00	XEROX CORPORATION
        ///00-00-01	XEROX CORPORATION
        ///00-00-02	XEROX CORPORATION
        ///00-00-03	XEROX CORPORATION
        ///00-00-04	XEROX CORPORATION
        ///00-00-05	XEROX CORPORATION
        ///00-00-06	XEROX CORPORATION
        ///00-00-07	XEROX CORPORATION
        ///00-00-08	XEROX CORPORATION
        ///00-00-09	XEROX CORPORATION
        ///00-00-0A	OMRON TATEISI ELECTRONICS CO.
        ///00-00-0B	MATRIX CORPORATION
        ///00-00-0C	CISCO SYSTEMS, INC.
        ///00-00-0D	FIBRONICS LTD.
        ///00-00-0E	FUJITSU LIMITED
        ///00-00-0F	NEXT, INC.
        ///00-00-10	SYTEK INC.
        ///00-00-11	NORMEREL SYSTEMES
        ///00-00-12	INF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MACs {
            get {
                return ResourceManager.GetString("MACs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
        ///
        ////**
        /// * 1. Set default font family to sans-serif.
        /// * 2. Prevent iOS and IE text size adjust after device orientation change,
        /// *    without disabling user zoom.
        /// */
        ///
        ///html {
        ///  font-family: sans-serif; /* 1 */
        ///  -ms-text-size-adjust: 100%; /* 2 */
        ///  -webkit-text-size-adjust: 100%; /* 2 */
        ///}
        ///
        ////**
        /// * Remove default margin.
        /// */
        ///
        ///body {
        ///  margin: 0;
        ///}
        ///
        ////* HTML5 display definitions
        ///   ================================ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string normalize {
            get {
                return ResourceManager.GetString("normalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Report styling created by: Devon Ackerman */
        ////*                  Last updated: 2016.02.14 */
        ///
        ///Container {
        ///	width: 1400px;
        ///	height: auto;
        ///	border: medium #146B99 solid;
        ///	resize: both;
        ///	overflow: auto;
        ///	min-width: 50px;  /* min-width  */
        ///	min-height: 50px; /* min-height */
        ///	display: block;
        ///	padding: 0;
        ///	margin: 10px;
        ///	background-color: #E9F0F4;
        ///}
        ///
        ///Container:before {
        ///  display: block;
        ///  width: auto;
        ///  font-weight: bold;
        ///  font-size: 24px;
        ///  content: &quot;.LNK File&quot;;
        ///  background-color: #1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
    }
}
